# Generated by Django 5.1.1 on 2024-09-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_product_total_sales_product_total_sales_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/images"),
        ),
        migrations.AlterField(
            model_name="product",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/files"),
        ),
    ]
